rootProject.name = 'auth'

dependencyResolutionManagement.versionCatalogs {
    libs {
        library("dependencies", "com.mcst:easyfk-dependencies:3.2.12")
        library('lombok', 'org.projectlombok:lombok:1.18.38')
        library('lombokMapstruct', 'org.projectlombok:lombok-mapstruct-binding:0.2.0')
        library('mapstructProcessor', 'io.github.linpeilie:mapstruct-plus-processor:1.5.0')
        library('processor', 'org.springframework.boot:spring-boot-configuration-processor:3.2.12')
    }
}


include 'auth-server'
include 'auth-api'

include 'auth-orm'
include 'auth-orm:auth-orm-api'
findProject(':auth-orm:auth-orm-api')?.name = 'auth-orm-api'
include 'auth-orm:auth-orm-plus'
findProject(':auth-orm:auth-orm-plus')?.name = 'auth-orm-plus'
include 'auth-orm:auth-orm-flex'
findProject(':auth-orm:auth-orm-flex')?.name = 'auth-orm-flex'
include 'auth-orm:auth-orm-hibernate'
findProject(':auth-orm:auth-orm-hibernate')?.name = 'auth-orm-hibernate'

include 'auth-remote'
include 'auth-remote:auth-cloud-api'
findProject(':auth-remote:auth-cloud-api')?.name = 'auth-cloud-api'
include 'auth-remote:auth-cloud-provider'
findProject(':auth-remote:auth-cloud-provider')?.name = 'auth-cloud-provider'
include 'auth-remote:auth-dubbo-api'
findProject(':auth-remote:auth-dubbo-api')?.name = 'auth-dubbo-api'
include 'auth-remote:auth-dubbo-provider'
findProject(':auth-remote:auth-dubbo-provider')?.name = 'auth-dubbo-provider'

include 'auth-prd'