rootProject.name = 'auth'

dependencyResolutionManagement.versionCatalogs {
    libs {
        library("dependencies", "com.mcst:easyfk-dependencies:3.2.12")
        library('lombok', 'org.projectlombok:lombok:1.18.38')
        library('processor', 'org.springframework.boot:spring-boot-configuration-processor:3.2.12')
    }
}


include 'auth-server'
include 'auth-api'

include 'auth-sc'
include 'auth-sc:auth-sc-client'
findProject(':auth-sc:auth-sc-client')?.name = 'auth-sc-client'
include 'auth-sc:auth-sc-provider'
findProject(':auth-sc:auth-sc-provider')?.name = 'auth-sc-provider'
include 'auth-prd'
include 'auth-sc:resource-sc-client'