dependencies {
    api project(':auth-api')
    api('com.mcst:easyfk-authority')
    api project(':auth-orm:auth-orm-api')
    api('com.mcst:service-base')
    api('com.mcst:login-server')
    compileOnly('org.springframework:spring-tx')
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

test {
    useJUnitPlatform()
}

